### ISSUE TITLE
Provide a precompiled binary?`

### ISSUE THREAD

**Issue by MH15** [xi-editor/xi-win#13]
It'd be nice.

**Comment by MH15** [comment]
Seeing the response to this I'd be willing to do this when I get a chance. I'll look into this.

**Comment by Crypec** [comment]
I agree a precompiled binary would be great.

**Comment by spikespaz** [comment]
Not downloading and setting up a Rust environment just to use this. Precompiled binaries please, should be standard across software like this.

**Comment by joelhandwell** [comment]
And a https://chocolatey.org/ package will enable users to install it with command ```choco install xi```

**Comment by fg123** [comment]
Could setup a Travis or Jarvis build to create bleeding edge binaries from the source code on each master commit...

**Comment by joelhandwell** [comment]
Or https://www.appveyor.com/ is focused on windows compared to Travis. It's possible to automate from git push, run tests, build binary, create and chocolatey package.

**Comment by LiHRaM** [comment]
Currently this project is in its development stages. It is definitely _not_ ready for casual use. You can probably expect a pre-compiled binary when this changes. Closing this for now.

**Comment by spikespaz** [comment]
@LiHRaM That's why there's a checkbox that says "pre-release" when making a new tag release on GitHub.

Boo.
