### ISSUE TITLE
Resize the viewport depending on the window size

### ISSUE THREAD

**Issue by pforpallav** [xi-editor/xi-win#4]
Resize the viewport depending on the window size. Add support for tracking the current start line for the view and request required number of lines based on the window height.

**Comment by pforpallav** [comment]
![viewport_xi_win](https://user-images.githubusercontent.com/1752025/28038883-3fc528c8-6575-11e7-963f-4d83a5cb0e6e.gif)

**Comment by Boscop** [comment]
Also it should scroll horizontally when the cursor on a long line moves outside of the viewport.
(And it should have an auto word wrap option IMO..)

**Comment by LiHRaM** [comment]
Closing this for now, it seems like the original issue has been resolved. New issues will be made for horizontal scrolling, etc. when the time comes.
