### ISSUE TITLE
CLA still necessary?

### ISSUE THREAD

**Issue by LiHRaM** [xi-editor/xi-win#46]
I noticed today that `Contributing.md` still references the Google CLA.
I would like to update that for you, but am not sure what you would prefer instead. Should we just refer to the one in `xi-editor`, maybe?

**Comment by raphlinus** [comment]
Feel free to update. The contribution rules are not identical to those of xi-editor; among other things the review requirements are not as strict (I can push directly). However, the CLA is no longer necessary, as you observe.

Note that I expect the contribution rules to evolve; they could converge with those for xi-editor once there's a critical mass of people who can review each other's code.

**Comment by LiHRaM** [comment]
Question has been answered, but a new issue should probably be made for establishing a process.
