### ISSUE TITLE
Rework xi-win to be on top of xi-win-ui

### ISSUE THREAD

**Issue by raphlinus** [xi-editor/xi-win#49]
Right now xi-win is implemented directly on top of xi-win-shell, and implements its `WinHandler` trait. This won't scale, and should be reworked to be a xi-win-ui app. Note: I did this work, but seem to have lost the git branch in the confusion of the repo move. Here I'll try to outline the major pieces of work needed.

The main work is changing `EditView` to implement xi-win-ui's `Widget` trait. This trait is roughly similar to the existing code - both are concerned with consuming mouse, kb, and other events (including resize), and painting the edit view. Of course, there are other tricky bits.

The central tricky bit is handling the `Core` state and plumbing it to the `EditView` so the latter can send notifications (implementing various edit commands) and also receive updates. The most straightforward way to do this is to wrap it in an `Arc<Mutex<>>` so that all `EditView` instances share a reference. There may be other, more "data-oriented" ways to do it, or it's possible to use a non-thread-safe shared reference, but doing it this way is most similar to xi-mac.

For the EditView to receive updates from core, there needs to be a way to send events into the UI from the outside. In my lost patch, I had an `ext_listener` which was parallel to the existing `command_listener`, and it was also thread-safe. One of the subtasks is to recreate that. (Note that it's required for the synthesizer as well, so the UI can respond to external MIDI and possibly to events generated by the synthesis thread).

Another tricky bit is implementation of the file commands. The file dialogs themselves are in a bit of a hacky state, as they're implemented in xi-win-shell but not xi-win-ui, and require a raw HWND handle. This can be hacked, but it should be made cleaner.

We should anticipate multiple EditView instances. There will be a "current" instance (similar to focus, but it's possible there's a current EditView even if, for example, there's a find dialog open that has focus), and commands should be forwarded to the current instance.

I'm happy to have help on this, and also happy to answer questions. I can take on any chunks that seem daunting though; it's certainly not a trivial refactor, and it intersects with a bunch of other things needing work (see #44 for example).

**Comment by LiHRaM** [comment]
I'd like to start work on reworking it into a xi-win-ui app - I can see you've already implemented the `ext_listener` - should I base my branch off of that one?

**Comment by raphlinus** [comment]
Yes, or we can just merge the PR; it's mostly up there in case you had any questions or concerns about it.

Glad to have you working on it!

**Comment by LiHRaM** [comment]
Okay, sounds good.
I have a question in regards to this issue, though. Am I correct to assume that we'll want to remove any dependencies xi-win has directly on winapi/xi-win-shell, and that xi-win can expect all of that behavior to be implemented via xi-win-ui?

**Comment by raphlinus** [comment]
@LiHRaM I might want to work on this again, is that ok? Or if there's something I can do to help, let me know.

**Comment by LiHRaM** [comment]
@raphlinus Totally fine if you want to work on this. :)

**Comment by LiHRaM** [comment]
Not sure when we should consider this issue closed, but as you mentioned multiple EditViews, maybe that would be an appropriate point?

It would be possible to start that once #45 and #59 are merged.

**Comment by raphlinus** [comment]
Nah, I think we can consider this closed by #58, because multiple EditViews is certainly not something that was working before. I've just been committing stuff, but since this is becoming more of a collaborative project we can totally have tracking issues for features we're working on.

**Comment by LiHRaM** [comment]
Okay, I'll close it then.
